sudo: false
os:
  - linux
  - osx
language: rust
rust:
  - 1.8.0
  - 1.15.0
  - 1.20.0
  - stable
  - beta
  - nightly
matrix:
  exclude:
    - os: osx
      rust: 1.8.0
script:
  - cargo build --verbose
  - cargo test --verbose
